"""
FastAPI backend for the RAG Financial Data Assistant.

Endpoints
---------
GET  /health          Liveness + readiness probe.
GET  /tickers         List of supported equity tickers.
POST /query           RAG query returning a full JSON response.
POST /query/stream    RAG query over Server-Sent Events (token streaming).
"""

from __future__ import annotations

import logging
import os
import time
from contextlib import asynccontextmanager
from typing import Any, AsyncIterator

from fastapi import FastAPI, HTTPException, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field, field_validator

from pipeline.rag_chain import CHAT_MODEL, RETRIEVAL_K, SYSTEM_PROMPT, _vectorstore, build_chain
from pipeline.rag_chain import query as rag_query

logging.basicConfig(
    level=os.getenv("LOG_LEVEL", "INFO"),
    format="%(asctime)s %(levelname)s %(name)s — %(message)s",
)
logger = logging.getLogger(__name__)

SUPPORTED_TICKERS: list[str] = [
    "AAPL", "MSFT", "GOOGL", "AMZN", "META",
    "TSLA", "NVDA", "JPM", "V", "JNJ",
]


# ── Lifespan ───────────────────────────────────────────────────────────────

@asynccontextmanager
async def lifespan(app: FastAPI) -> AsyncIterator[None]:
    """Pre-warm the RAG chain on startup so the first request isn't cold."""
    try:
        build_chain()
        logger.info("RAG chain warmed up successfully.")
    except Exception as exc:  # noqa: BLE001
        logger.warning("Chain warmup failed (will retry on first request): %s", exc)
    yield
    # Cleanup on shutdown (nothing stateful to release; ChromaDB client is GC'd).


# ── App ────────────────────────────────────────────────────────────────────

app = FastAPI(
    title="RAG Financial Data Assistant",
    version="1.0.0",
    description=(
        "Ask natural-language questions about AAPL, MSFT, GOOGL, AMZN, META, "
        "TSLA, NVDA, JPM, V, and JNJ. Answers are grounded in daily OHLCV "
        "data stored in ChromaDB and generated by GPT-4o-mini."
    ),
    docs_url="/docs",
    redoc_url="/redoc",
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=os.getenv("CORS_ORIGINS", "http://localhost:8501").split(","),
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ── Schemas ────────────────────────────────────────────────────────────────

class QueryRequest(BaseModel):
    question: str = Field(
        ...,
        min_length=5,
        max_length=500,
        description="Natural language financial question.",
        examples=["What is the 30-day trend for NVDA?"],
    )
    ticker_filter: list[str] | None = Field(
        default=None,
        description="Restrict retrieval context to these tickers.",
        examples=[["AAPL", "MSFT"]],
    )

    @field_validator("ticker_filter")
    @classmethod
    def validate_tickers(cls, v: list[str] | None) -> list[str] | None:
        if v is None:
            return v
        v = [t.upper() for t in v]
        invalid = [t for t in v if t not in SUPPORTED_TICKERS]
        if invalid:
            raise ValueError(
                f"Unsupported ticker(s): {invalid}. Supported: {SUPPORTED_TICKERS}"
            )
        return v


class SourceDoc(BaseModel):
    ticker: str
    trade_date: str
    trend_signal: str
    volatility_bucket: str
    snippet: str


class QueryResponse(BaseModel):
    answer: str
    sources: list[SourceDoc]
    latency_ms: float


class HealthResponse(BaseModel):
    status: str
    version: str
    chain_ready: bool


# ── Routes ─────────────────────────────────────────────────────────────────

@app.get("/health", response_model=HealthResponse, tags=["ops"])
async def health() -> HealthResponse:
    """Liveness and readiness probe used by Docker Compose and Kubernetes."""
    chain_ready = True
    try:
        build_chain()
    except Exception:  # noqa: BLE001
        chain_ready = False

    return HealthResponse(
        status="ok" if chain_ready else "degraded",
        version=app.version,
        chain_ready=chain_ready,
    )


@app.get("/tickers", tags=["data"])
async def list_tickers() -> dict[str, list[str]]:
    """Return the list of supported equity tickers."""
    return {"tickers": SUPPORTED_TICKERS}


@app.post("/query", response_model=QueryResponse, tags=["rag"])
async def query_endpoint(request: QueryRequest) -> QueryResponse:
    """
    Answer a financial question using retrieval-augmented generation.

    Retrieves the most semantically relevant stock-data chunks from ChromaDB
    (MMR, k=6) and generates a grounded response via GPT-4o-mini.
    """
    t0 = time.perf_counter()
    try:
        result = rag_query(
            question=request.question,
            ticker_filter=request.ticker_filter,
        )
    except Exception as exc:
        logger.exception("RAG query failed: %s", exc)
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="RAG pipeline temporarily unavailable. Please retry.",
        ) from exc

    latency_ms = round((time.perf_counter() - t0) * 1000, 1)
    logger.info(
        "Query answered in %.0f ms | tickers=%s | q=%r",
        latency_ms, request.ticker_filter, request.question[:80],
    )

    return QueryResponse(
        answer=result["answer"],
        sources=[SourceDoc(**s) for s in result["sources"]],
        latency_ms=latency_ms,
    )


@app.post("/query/stream", tags=["rag"])
async def query_stream(request: QueryRequest) -> StreamingResponse:
    """
    Streaming SSE endpoint — yields answer tokens as they are generated.

    Each event has the form ``data: <token>\\n\\n``.
    A final ``data: [DONE]\\n\\n`` signals completion.
    """

    async def token_generator() -> AsyncIterator[str]:
        from langchain_core.prompts import ChatPromptTemplate
        from langchain_openai import ChatOpenAI

        vs = _vectorstore()
        retriever = vs.as_retriever(
            search_type="mmr",
            search_kwargs={"k": RETRIEVAL_K, "fetch_k": RETRIEVAL_K * 3},
        )
        context_docs = retriever.invoke(request.question)
        context_text = "\n\n---\n\n".join(d.page_content for d in context_docs)

        llm = ChatOpenAI(model=CHAT_MODEL, temperature=0.1, streaming=True)
        prompt = ChatPromptTemplate.from_messages(
            [
                ("system", SYSTEM_PROMPT.replace("{context}", context_text)),
                ("human", "{input}"),
            ]
        )
        chain = prompt | llm

        async for chunk in chain.astream({"input": request.question}):
            if hasattr(chunk, "content") and chunk.content:
                yield f"data: {chunk.content}\n\n"

        yield "data: [DONE]\n\n"

    return StreamingResponse(token_generator(), media_type="text/event-stream")
