FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    fastapi uvicorn pydantic python-dotenv \
    langchain==0.2.14 \
    langchain-core \
    langchain-chroma \
    langchain-groq \
    langchain-huggingface \
    langchain-community \
    chromadb \
    sentence-transformers \
    google-cloud-bigquery \
    yfinance pandas

COPY pipeline/ ./pipeline/
COPY app/ ./app/

EXPOSE 8000

CMD ["uvicorn", "app.api.main:app", "--host", "0.0.0.0", "--port", "8000"]
